plugins:
  - serverless-s3-sync
  - serverless-plugin-ifelse

service: swansea-kendo-club-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: ${opt:stage, 'update-test'}
  deploymentBucket:
    name: com.serverless.${self:provider.region}.dep.archive
  stackTags:
    website: swansea-kendo-site

custom:
  serverlessIfElse:
    - If: '"${self:provider.stage}" != "dev"'
      Set:
        resources.Resources.WebsiteDistribution.Properties.DistributionConfig.Aliases:
          - "${self:provider.stage}.${self:custom.websiteAlias}"
      ElseSet:
        resources.Resources.WebsiteDistribution.Properties.DistributionConfig.Aliases:
          - www.${self:custom.websiteAlias}
          - ${self:custom.websiteAlias}
          
  websiteAlias: "swansea-kendo.club"
  stagedWebsiteAlias: "${self:provider.stage}.${self:custom.websiteAlias}"
  objectPrefix: '${self:provider.stage}-${self:service}'
  s3Sync:
    - bucketName: '${self:custom.objectPrefix}'
      localDir: _site
      defaultContentType: text/html # optional

package:
  exclude:
    - ./**

resources:
  - ${file(resources/cognito-resources.yml)}
  - ${file(resources/website-distribution.yml)}
 
