plugins:
  - serverless-s3-sync

service: swansea-kendo-club-serverless

provider:
  name: aws
  runtime: nodejs24.x
  region: eu-west-2
  stage: ${opt:stage, 'update-test'}
  deploymentBucket:
    name: com.serverless.${self:provider.region}.dep.archive
  stackTags:
    website: swansea-kendo-site

custom:
  websiteAlias: "swansea-kendo.club"
  objectPrefix: '${self:provider.stage}-${self:service}'
  s3Sync:
    - bucketName: '${self:custom.objectPrefix}'
      localDir: _site
      defaultContentType: text/html
  aliases:
    prod:
      - www.swansea-kendo.club
      - swansea-kendo.club
    other:
      - ${self:provider.stage}.swansea-kendo.club

package:
  exclude:
    - ./**

resources:
  - ${file(resources/website-distribution.yml)}
