plugins:
  - serverless-s3-sync
  - serverless-plugin-cloudfront-lambda-edge

service: swansea-kendo-club-serverless

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  deploymentBucket:
    name: com.serverless.${self:provider.region}.dep.archive
  stackTags:
    website: swansea-kendo-site

custom:
  websiteAlias: "swansea-kendo.club"
  objectPrefix: '${self:provider.stage}-${self:service}'
  s3Sync:
    - bucketName: '${self:custom.objectPrefix}'
      localDir: _site
      defaultContentType: text/html # optional
#  customDomain:
#    domainName: api.swansea-kendo.club
#    certificateName: 'api.${self:custom.websiteAlias}'
#    basePath: ''
#    stage: ${self:provider.stage}
#    createRoute53Record: true
#  customCertificate:
#    certificateName: 'api.${self:custom.websiteAlias}'
#    hostedZoneId: 'ZLXG9P4B2IVKD'

package:
  excludeDevDependency: true
  individually: true
  exclude:
    - ./**

resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: '${self:custom.objectPrefix}'
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteBucket
        PolicyDocument:
          Statement:
            -
              Action:
                - "s3:GetObject"
              Effect: Allow
              Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { Ref: WebsiteBucket }, "/*"]] }
              Principal:
                AWS: { "Fn::Join" : [" ", ["arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity", { Ref: WebsiteOriginAccessIdentity } ] ] } 
    WebsiteOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "Origin Access Identity"
    WebsiteDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.websiteAlias}
            - www.${self:custom.websiteAlias}
          DefaultCacheBehavior:
            TargetOriginId: 'WebsiteBucketOrigin'
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 600 # ten minutes
            MaxTTL: 600 # ten minutes
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
          CacheBehaviors:
            -
              TargetOriginId: 'WebsiteBucketOrigin'
              PathPattern: '*'
              ViewerProtocolPolicy: 'redirect-to-https'
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: 'none'
              DefaultTTL: 0
              MaxTTL: 0
          DefaultRootObject: 'index.html'
          Enabled: true
          PriceClass: 'PriceClass_100'
          HttpVersion: 'http2' 
          ViewerCertificate:
            SslSupportMethod: "sni-only"
            AcmCertificateArn: ${ssm:swansea-kendo-club-base-cert}
          Origins:
            -
              Id: 'WebsiteBucketOrigin'
              DomainName: { 'Fn::GetAtt': [ 'WebsiteBucket', 'DomainName' ] }
              S3OriginConfig:
                OriginAccessIdentity: { "Fn::Join": ["", ["origin-access-identity/cloudfront/", { Ref: WebsiteOriginAccessIdentity } ] ] }
