version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.0.0
  serverless-framework: circleci/serverless-framework@2.0
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Build Static Site Assets
          command: |
            cd swansea-kendo-serverless
            bundle install
            bundle exec jekyll build
      
  deploy:
    executor: serverless-framework/default
    environment:
      AWS_DEFAULT_REGION: "eu-west-2"
    steps:
      - aws-cli/install
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - run:
          name: Run tests with code coverage
          command: npm run test

      - run:
          name: Verify Credentials
          command: aws sts get-caller-identity
    #   - run:
    #       name: Deploy application
    #       command: sls deploy --region ${AWS_DEFAULT_REGION}



workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          context:
            - Serverless Development
          # filters:
          #   branches:
          #     only: main # Only deploy when the commit is on the Ma